version: '2'

services:
  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root123  
        
  app:
    container_name: ${PHP_CONTAINER_NAME}
    build: .docker/php
    volumes:
      - .:/app
      - ./var/logs:/app/var/logs
      - ./var/cache.:/app/var/cache

  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    build: .docker/nginx
    volumes_from:
      - app
    ports:
      - "${PORT_NUMBER}:80"
