<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4uwnqhl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4uwnqhl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4uwnqhl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4uwnqhl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4uwnqhl\appDevDebugProjectContainer(array(
    'container.build_hash' => '4uwnqhl',
    'container.build_id' => 'eb6da912',
    'container.build_time' => 1527498378,
), __DIR__.\DIRECTORY_SEPARATOR.'Container4uwnqhl');
