<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHkia0k1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHkia0k1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHkia0k1.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHkia0k1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHkia0k1\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hkia0k1',
    'container.build_id' => '57b0aacb',
    'container.build_time' => 1527572836,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHkia0k1');
